version: "3.8"

services:
  app:
    image: denis88dev/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["npm", "test"]

volumes:
  app:
