version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'sleep 3 && npm start'
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  caddy:
    image: caddy:2.7.6
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  caddy_data:
