services:
  app-dev:
    extends:
      file: docker-compose.yml
      service: app
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app

  caddy:
    image: caddy:2.7.6
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app-dev

volumes:
  caddy_data:
