name: push

on:
  push:
    branches:
      - main

env:
  APP_IMAGE_NAME: denis88dev/devops-for-programmers-project-74

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Run action checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run tests
        run: make ci

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}
          cache-to: type=inline
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest
